import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
await page.goto('https://vportal-uat.aqaar.com/signin');
await page.getByTestId('username').fill('saidheer.adabal@gmail.com');
await page.getByTestId('username').press('Tab');
await page.getByTestId('password').press('CapsLock');
await page.getByTestId('password').fill('A');
await page.getByTestId('password').press('CapsLock');
await page.getByTestId('password').fill('Aqaar@123');
await page.getByRole('button', { name: 'Sign In' }).click();
await page.getByTestId('username').click();
await page.getByTestId('username').press('ArrowLeft');
await page.getByTestId('username').press('ArrowLeft');
await page.getByTestId('username').press('ArrowLeft');
await page.getByTestId('username').press('ArrowLeft');
await page.getByTestId('username').press('ArrowLeft');
await page.getByTestId('username').press('ArrowLeft');
await page.getByTestId('username').press('ArrowLeft');
await page.getByTestId('username').press('ArrowLeft');
await page.getByTestId('username').press('ArrowLeft');
await page.getByTestId('username').press('ArrowLeft');
await page.getByTestId('username').press('ArrowLeft');
await page.getByTestId('username').press('ArrowRight');
await page.getByTestId('username').fill('saidheer.adabala@gmail.com');
await page.getByTestId('password').click();
await page.getByRole('button', { name: 'Sign In' }).click();
await page.getByTestId('username').click();
await page.getByTestId('username').press('ArrowLeft');
await page.getByTestId('username').press('ArrowLeft');
await page.getByTestId('username').press('ArrowLeft');
await page.getByTestId('username').press('ArrowLeft');
await page.getByTestId('username').press('ArrowLeft');
await page.getByTestId('username').press('ArrowRight');
await page.getByTestId('username').fill('saidheer.adabala@prokraya.com');
await page.getByTestId('password').click();
await page.getByRole('button', { name: 'Sign In' }).click();
await page.getByRole('link', { name: 'Requisitions' }).click();
await page.getByText('PR/0021294').click();
await page.getByRole('link').filter({ hasText: /^$/ }).click();
await page.locator('.fa-regular').first().click();
await page.getByRole('link', { name: 'Logout' }).click();
});